Delete_user=Label(root,text="Delete User",font=('Sitka Small', 15, 'bold'))
        # user_delete_label=Label(root,text="Username",font=("Arial",15))
        # Delete_button=Button(root,text="Delete",width=20, padx=7,command=delete_user, pady=5, bg="#B33030", fg="white", font=('calibre', 10, 'bold'))
        # Delete_user.place(x=330,y=480,height=28)
        # user_delete_label.place(x=200,y=530)
        # delete.place(x=330,y=540)
        # Delete_button.place(x=550,y=580)